# Data Cleaning and Wrangling for MongoDB database population

### data source: goodbooks-10k & goodreads_data_genre.csv

In [1]:
import pandas as pd

In [2]:
gb_ratings_df = pd.read_csv("../goodbooks-10k/ratings.csv")
gb_ratings_df.head()
# gb_ratings_df[gb_ratings_df["book_id"] == 5397]

   user_id  book_id  rating
0        1      258       5
1        2     4081       4
2        2      260       5
3        2     9296       5
4        2     2318       3

In [3]:
gb_books_df = pd.read_csv("../goodbooks-10k/books.csv")
gb_books_df.head()
# gb_books_df[gb_books_df["work_id"] == 5397]

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

In [4]:
# Merge
merged_books_ratings = pd.merge(gb_books_df, gb_ratings_df, left_on='work_id', right_on='book_id', how='inner')
merged_books_ratings.dropna()

merged_books_ratings

,book_id_x,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,user_id,book_id_y,rating
0,92,1202,1202,5397,124,61234001,9.780061e+12,"Steven D. Levitt, Stephen J. Dubner",2005.0,Freakonomics: A Rogue Economist Explores the H...,...,14586,26538,115789,216316,176072,https://images.gr-assets.com/books/1327909092m...,https://images.gr-assets.com/books/1327909092s...,807,5397,3
1,92,1202,1202,5397,124,61234001,9.780061e+12,"Steven D. Levitt, Stephen J. Dubner",2005.0,Freakonomics: A Rogue Economist Explores the H...,...,14586,26538,115789,216316,176072,https://images.gr-assets.com/books/1327909092m...,https://images.gr-assets.com/books/1327909092s...,1942,5397,2
2,92,1202,1202,5397,124,61234001,9.780061e+12,"Steven D. Levitt, Stephen J. Dubner",2005.0,Freakonomics: A Rogue Economist Explores the H...,...,14586,26538,115789,216316,176072,https://images.gr-assets.com/books/1327909092m...,https://images.gr-assets.com/books/1327909092s...,85,5397,3
3,92,1202,1202,5397,124,61234001,9.780061e+12,"Steven D. Levitt, Stephen J. Dubner",2005.0,Freakonomics: A Rogue Economist Explores the H...,...,14586,26538,115789,216316,176072,https://images.gr-assets.com/books/1327909092m...,https://images.gr-assets.com/books/1327909092s...,1605,5397,2
4,92,1202,1202,5397,124,61234001,9.780061e+12,"Steven D. Levitt, Stephen J. Dubner",2005.0,Freakonomics: A Rogue Economist Explores the H...,...,14586,26538,115789,216316,176072,https://images.gr-assets.com/books/1327909092m...,https://images.gr-assets.com/books/1327909092s...,2546,5397,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130181,9973,849380,849380,4370,52,609805797,9.780610e+12,"John M. Gottman, Nan Silver",1999.0,The Seven Principles for Making Marriage Work:...,...,126,334,1604,3446,4507,https://images.gr-assets.com/books/1320521960m...,https://images.gr-assets.com/books/1320521960s...,2751,4370,4
130182,9973,849380,849380,4370,52,609805797,9.780610e+12,"John M. Gottman, Nan Silver",1999.0,The Seven Principles for Making Marriage Work:...,...,126,334,1604,3446,4507,https://images.gr-assets.com/books/1320521960m...,https://images.gr-assets.com/books/1320521960s...,50182,4370,5
130183,9973,849380,849380,4370,52,609805797,9.780610e+12,"John M. Gottman, Nan Silver",1999.0,The Seven Principles for Making Marriage Work:...,...,126,334,1604,3446,4507,https://images.gr-assets.com/books/1320521960m...,https://images.gr-assets.com/books/1320521960s...,31548,4370,4
130184,9973,849380,849380,4370,52,609805797,9.780610e+12,"John M. Gottman, Nan Silver",1999.0,The Seven Principles for Making Marriage Work:...,...,126,334,1604,3446,4507,https://images.gr-assets.com/books/1320521960m...,https://images.gr-assets.com/books/1320521960s...,29867,4370,5
130185,9973,849380,849380,4370,52,609805797,9.780610e+12,"John M. Gottman, Nan Silver",1999.0,The Seven Principles for Making Marriage Work:...,...,126,334,1604,3446,4507,https://images.gr-assets.com/books/1320521960m...,https://images.gr-assets.com/books/1320521960s...,39864,4370,5

In [5]:
merged_books_ratings_cleaned = merged_books_ratings[["isbn", "user_id", "rating"]]
merged_books_ratings_cleaned.head()

       isbn  user_id  rating
0  61234001      807       3
1  61234001     1942       2
2  61234001       85       3
3  61234001     1605       2
4  61234001     2546       3

In [29]:
reduced_merged_books_ratings = pd.merge(better_reads_df, merged_books_ratings_cleaned, left_on='ISBN', right_on='isbn', how='inner')
reduced_merged_books_ratings_cleaned = reduced_merged_books_ratings[["isbn", "user_id", "rating"]]
reduced_merged_books_ratings_cleaned

            isbn  user_id  rating
0      307346609      379       5
1      307346609      599       4
2      307346609      781       4
3      307346609      861       4
4      307346609      791       3
...          ...      ...     ...
60659  571198775    11296       4
60660  571198775    52758       3
60661  571198775    51092       3
60662  571198775    43711       3
60663  571198775     7948       3

[60664 rows x 3 columns]

In [30]:
isbn_book_id = pd.read_json("better-reads/backend/data/bookIdToIsbnMap.json")
isbn_book_id

,6861eac7f73dac107c42d926,6861eac7f73dac107c42d927,6861eac7f73dac107c42d928,6861eac7f73dac107c42d929,6861eac7f73dac107c42d92a,6861eac7f73dac107c42d92b,6861eac7f73dac107c42d92c,6861eac7f73dac107c42d92d,6861eac7f73dac107c42d92e,6861eac7f73dac107c42d92f,...,6861eac7f73dac107c42e745,6861eac7f73dac107c42e746,6861eac7f73dac107c42e747,6861eac7f73dac107c42e748,6861eac7f73dac107c42e749,6861eac7f73dac107c42e74a,6861eac7f73dac107c42e74b,6861eac7f73dac107c42e74c,6861eac7f73dac107c42e74d,6861eac7f73dac107c42e74e
ISBN,439023483,61120081,743273567,525478817,618260307,316769177,679783261,1594480001,62024035,451524934,...,739416383,679749845,1580050751,679750150,140255087,674017722,575113294,224079948,810983559,61711527
title,"The Hunger Games (The Hunger Games, #1)",To Kill a Mockingbird,The Great Gatsby,The Fault in Our Stars,The Hobbit,The Catcher in the Rye,Pride and Prejudice,The Kite Runner,"Divergent (Divergent, #1)",1984,...,"The Prize Winner of Defiance, Ohio: How My Mot...",The Comfort of Strangers,Cunt: A Declaration of Independence,The Sailor Who Fell from Grace with the Sea,The Snow Leopard,A Theory of Justice,"The Red Knight (The Traitor Son Cycle, #1)",The Time Traveller's Guide to Medieval England...,"The Everafter War (The Sisters Grimm, #7)",Cinderella Ate My Daughter: Dispatches from th...
author,Suzanne Collins,Harper Lee,F. Scott Fitzgerald,John Green,J.R.R. Tolkien,J.D. Salinger,Jane Austen,Khaled Hosseini,Veronica Roth,"George Orwell, Erich Fromm, Celâl Üster",...,Terry Ryan,Ian McEwan,"Inga Muscio, Betty Dodson","Yukio Mishima, John Nathan",Peter Matthiessen,John Rawls,Miles Cameron,Ian Mortimer,"Michael Buckley, Peter Ferguson",Peggy Orenstein

In [37]:
isbn_book_id_trans = isbn_book_id.T
isbn_book_id_map = isbn_book_id_trans.reset_index()
isbn_book_id_map

,index,ISBN,title,author
0,6861eac7f73dac107c42d926,439023483,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins
1,6861eac7f73dac107c42d927,61120081,To Kill a Mockingbird,Harper Lee
2,6861eac7f73dac107c42d928,743273567,The Great Gatsby,F. Scott Fitzgerald
3,6861eac7f73dac107c42d929,525478817,The Fault in Our Stars,John Green
4,6861eac7f73dac107c42d92a,618260307,The Hobbit,J.R.R. Tolkien
...,...,...,...,...
3620,6861eac7f73dac107c42e74a,674017722,A Theory of Justice,John Rawls
3621,6861eac7f73dac107c42e74b,575113294,"The Red Knight (The Traitor Son Cycle, #1)",Miles Cameron
3622,6861eac7f73dac107c42e74c,224079948,The Time Traveller's Guide to Medieval England...,Ian Mortimer
3623,6861eac7f73dac107c42e74d,810983559,"The Everafter War (The Sisters Grimm, #7)","Michael Buckley, Peter Ferguson"
3624,6861eac7f73dac107c42e74e,61711527,Cinderella Ate My Daughter: Dispatches from th...,Peggy Orenstein

In [43]:
reduced_merged_books_ratings_book_id = pd.merge(reduced_merged_books_ratings_cleaned, isbn_book_id_map, left_on='isbn', right_on='ISBN', how='inner')
reduced_merged_books_ratings_book_id
ratings_books = reduced_merged_books_ratings_book_id[["index", "user_id", "rating"]]
ratings_books = ratings_books.rename(columns={'index': 'book_id'})
ratings_books

                        book_id  user_id  rating
0      6861eac7f73dac107c42d9f2      379       5
1      6861eac7f73dac107c42d9f2      599       4
2      6861eac7f73dac107c42d9f2      781       4
3      6861eac7f73dac107c42d9f2      861       4
4      6861eac7f73dac107c42d9f2      791       3
...                         ...      ...     ...
60659  6861eac7f73dac107c42e71f    11296       4
60660  6861eac7f73dac107c42e71f    52758       3
60661  6861eac7f73dac107c42e71f    51092       3
60662  6861eac7f73dac107c42e71f    43711       3
60663  6861eac7f73dac107c42e71f     7948       3

[60664 rows x 3 columns]

In [47]:
# Pivot to user-item matrix
matrix = ratings_books.pivot_table(index="user_id", columns="book_id", values="rating").fillna(0)
matrix
matrix.to_json("better-reads/backend/data/initial-user-item-matrix.json")

In [48]:
matrix_read = pd.read_json("better-reads/backend/data/initial-user-item-matrix.json")
matrix_read

,6861eac7f73dac107c42d9f2,6861eac7f73dac107c42d9f7,6861eac7f73dac107c42d9fa,6861eac7f73dac107c42da34,6861eac7f73dac107c42da68,6861eac7f73dac107c42db05,6861eac7f73dac107c42db2f,6861eac7f73dac107c42db5a,6861eac7f73dac107c42dc0a,6861eac7f73dac107c42dc49,...,6861eac7f73dac107c42e60f,6861eac7f73dac107c42e61e,6861eac7f73dac107c42e62c,6861eac7f73dac107c42e639,6861eac7f73dac107c42e65c,6861eac7f73dac107c42e666,6861eac7f73dac107c42e674,6861eac7f73dac107c42e6a5,6861eac7f73dac107c42e6be,6861eac7f73dac107c42e71f
1,0,0,0,3,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53413,0,0,0,0,0,0,0,0,4,0,...,0,0,0,0,0,0,0,0,0,0
53415,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53416,0,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53417,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
53422,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [42]:
# exported to json file
ratings_books.to_json("better-reads/backend/data/ratings_books.json", orient="records", indent=4, force_ascii=False)

In [7]:
# list all the columns of the goodbook
print(gb_books_df.columns)

Index(['book_id', 'goodreads_book_id', 'best_book_id', 'work_id',
       'books_count', 'isbn', 'isbn13', 'authors', 'original_publication_year',
       'original_title', 'title', 'language_code', 'average_rating',
       'ratings_count', 'work_ratings_count', 'work_text_reviews_count',
       'ratings_1', 'ratings_2', 'ratings_3', 'ratings_4', 'ratings_5',
       'image_url', 'small_image_url'],
      dtype='object')

In [8]:
gb_books_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   book_id                    10000 non-null  int64
 1   goodreads_book_id          10000 non-null  int64
 2   best_book_id               10000 non-null  int64
 3   work_id                    10000 non-null  int64
 4   books_count                10000 non-null  int64
 5   isbn                       9300 non-null   object
 6   isbn13                     9415 non-null   float64
 7   authors                    10000 non-null  object
 8   original_publication_year  9979 non-null   float64
 9   original_title             9415 non-null   object
 10  title                      10000 non-null  object
 11  language_code              8916 non-null   object
 12  average_rating             10000 non-null  float64
 13  ratings_count              10000 non-null  int64
 14  work_ratings_count         10000 non-null  int64
 15  work_text_reviews_count    10000 non-null  int64
 16  ratings_1                  10000 non-null  int64
 17  ratings_2                  10000 non-null  int64
 18  ratings_3                  10000 non-null  int64
 19  ratings_4                  10000 non-null  int64
 20  ratings_5                  10000 non-null  int64
 21  image_url                  10000 non-null  object
 22  small_image_url            10000 non-null  object
dtypes: float64(3), int64(13), object(7)
memory usage: 1.8+ MB

In [9]:
gb_books_cleaned_df = gb_books_df[["isbn", "authors", "original_publication_year", "title", "average_rating", 'ratings_count', 'work_text_reviews_count', 'books_count',"image_url"]]
gb_books_cleaned_df.head()

,isbn,authors,original_publication_year,title,average_rating,ratings_count,work_text_reviews_count,books_count,image_url
0,439023483,Suzanne Collins,2008.0,"The Hunger Games (The Hunger Games, #1)",4.34,4780653,155254,272,https://images.gr-assets.com/books/1447303603m...
1,439554934,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Sorcerer's Stone (Harry P...,4.44,4602479,75867,491,https://images.gr-assets.com/books/1474154022m...
2,316015849,Stephenie Meyer,2005.0,"Twilight (Twilight, #1)",3.57,3866839,95009,226,https://images.gr-assets.com/books/1361039443m...
3,61120081,Harper Lee,1960.0,To Kill a Mockingbird,4.25,3198671,72586,487,https://images.gr-assets.com/books/1361975680m...
4,743273567,F. Scott Fitzgerald,1925.0,The Great Gatsby,3.89,2683664,51992,1356,https://images.gr-assets.com/books/1490528560m...

In [10]:
gb_books_genre_description_df = pd.read_csv("../goodbooks-10k/goodreads_descriptions_genres.csv")
gb_books_genre_description_df

,Unnamed: 0,Book,Author,Description,Genres,Avg_Rating,Num_Ratings,URL
0,0,To Kill a Mockingbird,Harper Lee,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...",4.27,"5,691,311",https://www.goodreads.com/book/show/2657.To_Ki...
1,1,Harry Potter and the Philosopher’s Stone (Harr...,J.K. Rowling,Harry Potter thinks he is an ordinary boy - un...,"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4.47,"9,278,135",https://www.goodreads.com/book/show/72193.Harr...
2,2,Pride and Prejudice,Jane Austen,"Since its immediate success in 1813, Pride and...","['Classics', 'Fiction', 'Romance', 'Historical...",4.28,"3,944,155",https://www.goodreads.com/book/show/1885.Pride...
3,3,The Diary of a Young Girl,Anne Frank,Discovered in the attic in which she spent the...,"['Classics', 'Nonfiction', 'History', 'Biograp...",4.18,"3,488,438",https://www.goodreads.com/book/show/48855.The_...
4,4,Animal Farm,George Orwell,Librarian's note: There is an Alternate Cover ...,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",3.98,"3,575,172",https://www.goodreads.com/book/show/170448.Ani...
...,...,...,...,...,...,...,...,...
9995,9995,"Breeders (Breeders Trilogy, #1)",Ashley Quigley,How far would you go? If human society was gen...,"['Dystopia', 'Science Fiction', 'Post Apocalyp...",3.44,276,https://www.goodreads.com/book/show/22085400-b...
9996,9996,Dynamo,Eleanor Gustafson,Jeth Cavanaugh is searching for a new life alo...,[],4.23,60,https://www.goodreads.com/book/show/20862902-d...
9997,9997,The Republic of Trees,Sam Taylor,This dark fable tells the story of four Englis...,"['Fiction', 'Horror', 'Dystopia', 'Coming Of A...",3.29,383,https://www.goodreads.com/book/show/891262.The...
9998,9998,"Waking Up (Healing Hearts, #1)",Renee Dyer,For Adriana Monroe life couldn’t get any bette...,"['New Adult', 'Romance', 'Contemporary Romance...",4.13,263,https://www.goodreads.com/book/show/19347252-w...
9999,9999,Bits and Pieces: Tales and Sonnets,Jas T. Ward,After demands of thousands of fans in various ...,[],5.00,36,https://www.goodreads.com/book/show/21302552-b...

In [11]:
gb_books_genre_description_df.columns

Index(['Unnamed: 0', 'Book', 'Author', 'Description', 'Genres', 'Avg_Rating',
       'Num_Ratings', 'URL'],
      dtype='object')

In [12]:
gb_books_genre_description_cleaned_df = gb_books_genre_description_df[['Book', 'Author', 'Description', 'Genres', 'Avg_Rating',
       'Num_Ratings']]
gb_books_genre_description_cleaned_df.head()

,Book,Author,Description,Genres,Avg_Rating,Num_Ratings
0,To Kill a Mockingbird,Harper Lee,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...",4.27,"5,691,311"
1,Harry Potter and the Philosopher’s Stone (Harr...,J.K. Rowling,Harry Potter thinks he is an ordinary boy - un...,"['Fantasy', 'Fiction', 'Young Adult', 'Magic',...",4.47,"9,278,135"
2,Pride and Prejudice,Jane Austen,"Since its immediate success in 1813, Pride and...","['Classics', 'Fiction', 'Romance', 'Historical...",4.28,"3,944,155"
3,The Diary of a Young Girl,Anne Frank,Discovered in the attic in which she spent the...,"['Classics', 'Nonfiction', 'History', 'Biograp...",4.18,"3,488,438"
4,Animal Farm,George Orwell,Librarian's note: There is an Alternate Cover ...,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...",3.98,"3,575,172"

In [13]:
# drop the duplicate rows
left = gb_books_cleaned_df.copy()
right = gb_books_genre_description_cleaned_df.copy()

# Lowercase columns
left['title_lower'] = left['title'].str.lower()
right['book_lower'] = right['Book'].str.lower()

# Drop duplicates
left = left.drop_duplicates(subset='title_lower')
right = right.drop_duplicates(subset='book_lower')

# Merge
merged_df = pd.merge(left, right, left_on='title_lower', right_on='book_lower', how='inner')

# Clean up
merged_df.drop(columns=['title_lower', 'book_lower'], inplace=True)

In [14]:
merged_df

,isbn,authors,original_publication_year,title,average_rating,ratings_count,work_text_reviews_count,books_count,image_url,Book,Author,Description,Genres,Avg_Rating,Num_Ratings
0,439023483,Suzanne Collins,2008.0,"The Hunger Games (The Hunger Games, #1)",4.34,4780653,155254,272,https://images.gr-assets.com/books/1447303603m...,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,"Could you survive on your own in the wild, wit...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",4.33,"7,963,002"
1,61120081,Harper Lee,1960.0,To Kill a Mockingbird,4.25,3198671,72586,487,https://images.gr-assets.com/books/1361975680m...,To Kill a Mockingbird,Harper Lee,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...",4.27,"5,691,311"
2,743273567,F. Scott Fitzgerald,1925.0,The Great Gatsby,3.89,2683664,51992,1356,https://images.gr-assets.com/books/1490528560m...,The Great Gatsby,F. Scott Fitzgerald,Alternate Cover Edition ISBN: 0743273567 (ISBN...,"['Classics', 'Fiction', 'School', 'Historical ...",3.93,"4,839,642"
3,525478817,John Green,2012.0,The Fault in Our Stars,4.26,2346404,140739,226,https://images.gr-assets.com/books/1360206420m...,The Fault in Our Stars,John Green,Despite the tumor-shrinking medical miracle th...,"['Young Adult', 'Romance', 'Fiction', 'Contemp...",4.15,"4,762,958"
4,618260307,J.R.R. Tolkien,1937.0,The Hobbit,4.25,2071616,37653,969,https://images.gr-assets.com/books/1372847500m...,The Hobbit,Chuck Dixon,"First published over 50 years ago, J.R.R. Tolk...","['Fantasy', 'Graphic Novels', 'Classics', 'Fic...",4.51,"219,962"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3739,674017722,John Rawls,1971.0,A Theory of Justice,3.91,8472,168,44,https://s.gr-assets.com/assets/nophoto/book/11...,A Theory of Justice,John Rawls,"Since it appeared in 1971, John Rawls's A Theo...","['Philosophy', 'Politics', 'Nonfiction', 'Law'...",3.95,"12,320"
3740,575113294,Miles Cameron,2012.0,"The Red Knight (The Traitor Son Cycle, #1)",4.12,8556,742,26,https://images.gr-assets.com/books/1348037761m...,"The Red Knight (The Traitor Son Cycle, #1)",Miles Cameron,Twenty eight florins a month is a huge price t...,"['Fantasy', 'Epic Fantasy', 'Fiction', 'High F...",4.10,"16,797"
3741,224079948,Ian Mortimer,2008.0,The Time Traveller's Guide to Medieval England...,3.99,9824,970,27,https://images.gr-assets.com/books/1328167619m...,The Time Traveller's Guide to Medieval England...,Ian Mortimer,Imagine you could get into a time machine and ...,"['History', 'Nonfiction', 'Medieval', 'Histori...",4.00,"22,859"
3742,810983559,"Michael Buckley, Peter Ferguson",2009.0,"The Everafter War (The Sisters Grimm, #7)",4.32,12493,455,2,https://images.gr-assets.com/books/1388278230m...,"The Everafter War (The Sisters Grimm, #7)",Michael Buckley,The Grimm family is caught in the midst of a w...,"['Fantasy', 'Middle Grade', 'Fairy Tales', 'My...",4.35,"16,398"
3743,61711527,Peggy Orenstein,2011.0,Cinderella Ate My Daughter: Dispatches from th...,3.65,11279,1988,7,https://images.gr-assets.com/books/1279214118m...,Cinderella Ate My Daughter: Dispatches from th...,Peggy Orenstein,The acclaimed author of the groundbreaking bes...,"['Nonfiction', 'Parenting', 'Feminism', 'Psych...",3.67,"15,973"

In [15]:
merged_df.columns

Index(['isbn', 'authors', 'original_publication_year', 'title',
       'average_rating', 'ratings_count', 'work_text_reviews_count',
       'books_count', 'image_url', 'Book', 'Author', 'Description', 'Genres',
       'Avg_Rating', 'Num_Ratings'],
      dtype='object')

In [16]:
# Finalized the book data for better_reads
better_reads_df = merged_df[['title','authors','original_publication_year','image_url','Description','Genres','isbn', 
       'books_count','average_rating', 'ratings_count','work_text_reviews_count']]
better_reads_df

,title,authors,original_publication_year,image_url,Description,Genres,isbn,books_count,average_rating,ratings_count,work_text_reviews_count
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,2008.0,https://images.gr-assets.com/books/1447303603m...,"Could you survive on your own in the wild, wit...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",439023483,272,4.34,4780653,155254
1,To Kill a Mockingbird,Harper Lee,1960.0,https://images.gr-assets.com/books/1361975680m...,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...",61120081,487,4.25,3198671,72586
2,The Great Gatsby,F. Scott Fitzgerald,1925.0,https://images.gr-assets.com/books/1490528560m...,Alternate Cover Edition ISBN: 0743273567 (ISBN...,"['Classics', 'Fiction', 'School', 'Historical ...",743273567,1356,3.89,2683664,51992
3,The Fault in Our Stars,John Green,2012.0,https://images.gr-assets.com/books/1360206420m...,Despite the tumor-shrinking medical miracle th...,"['Young Adult', 'Romance', 'Fiction', 'Contemp...",525478817,226,4.26,2346404,140739
4,The Hobbit,J.R.R. Tolkien,1937.0,https://images.gr-assets.com/books/1372847500m...,"First published over 50 years ago, J.R.R. Tolk...","['Fantasy', 'Graphic Novels', 'Classics', 'Fic...",618260307,969,4.25,2071616,37653
...,...,...,...,...,...,...,...,...,...,...,...
3739,A Theory of Justice,John Rawls,1971.0,https://s.gr-assets.com/assets/nophoto/book/11...,"Since it appeared in 1971, John Rawls's A Theo...","['Philosophy', 'Politics', 'Nonfiction', 'Law'...",674017722,44,3.91,8472,168
3740,"The Red Knight (The Traitor Son Cycle, #1)",Miles Cameron,2012.0,https://images.gr-assets.com/books/1348037761m...,Twenty eight florins a month is a huge price t...,"['Fantasy', 'Epic Fantasy', 'Fiction', 'High F...",575113294,26,4.12,8556,742
3741,The Time Traveller's Guide to Medieval England...,Ian Mortimer,2008.0,https://images.gr-assets.com/books/1328167619m...,Imagine you could get into a time machine and ...,"['History', 'Nonfiction', 'Medieval', 'Histori...",224079948,27,3.99,9824,970
3742,"The Everafter War (The Sisters Grimm, #7)","Michael Buckley, Peter Ferguson",2009.0,https://images.gr-assets.com/books/1388278230m...,The Grimm family is caught in the midst of a w...,"['Fantasy', 'Middle Grade', 'Fairy Tales', 'My...",810983559,2,4.32,12493,455
3743,Cinderella Ate My Daughter: Dispatches from th...,Peggy Orenstein,2011.0,https://images.gr-assets.com/books/1279214118m...,The acclaimed author of the groundbreaking bes...,"['Nonfiction', 'Parenting', 'Feminism', 'Psych...",61711527,7,3.65,11279,1988

In [17]:
# change the column names
better_reads_df = better_reads_df.rename(columns={
    'title': 'title',
    'authors': 'author',
    'original_publication_year': 'publishYear',
    'image_url': 'image',
    'Description': 'description',
    'Genres': 'genre',
    'isbn': 'ISBN',
    'books_count': 'numberOfEditions',
    'average_rating': 'averageRating',
    'ratings_count': 'ratingsCount',
    'work_text_reviews_count': 'reviewCount'
})

In [18]:
better_reads_df

,title,author,publishYear,image,description,genre,ISBN,numberOfEditions,averageRating,ratingsCount,reviewCount
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,2008.0,https://images.gr-assets.com/books/1447303603m...,"Could you survive on your own in the wild, wit...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",439023483,272,4.34,4780653,155254
1,To Kill a Mockingbird,Harper Lee,1960.0,https://images.gr-assets.com/books/1361975680m...,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...",61120081,487,4.25,3198671,72586
2,The Great Gatsby,F. Scott Fitzgerald,1925.0,https://images.gr-assets.com/books/1490528560m...,Alternate Cover Edition ISBN: 0743273567 (ISBN...,"['Classics', 'Fiction', 'School', 'Historical ...",743273567,1356,3.89,2683664,51992
3,The Fault in Our Stars,John Green,2012.0,https://images.gr-assets.com/books/1360206420m...,Despite the tumor-shrinking medical miracle th...,"['Young Adult', 'Romance', 'Fiction', 'Contemp...",525478817,226,4.26,2346404,140739
4,The Hobbit,J.R.R. Tolkien,1937.0,https://images.gr-assets.com/books/1372847500m...,"First published over 50 years ago, J.R.R. Tolk...","['Fantasy', 'Graphic Novels', 'Classics', 'Fic...",618260307,969,4.25,2071616,37653
...,...,...,...,...,...,...,...,...,...,...,...
3739,A Theory of Justice,John Rawls,1971.0,https://s.gr-assets.com/assets/nophoto/book/11...,"Since it appeared in 1971, John Rawls's A Theo...","['Philosophy', 'Politics', 'Nonfiction', 'Law'...",674017722,44,3.91,8472,168
3740,"The Red Knight (The Traitor Son Cycle, #1)",Miles Cameron,2012.0,https://images.gr-assets.com/books/1348037761m...,Twenty eight florins a month is a huge price t...,"['Fantasy', 'Epic Fantasy', 'Fiction', 'High F...",575113294,26,4.12,8556,742
3741,The Time Traveller's Guide to Medieval England...,Ian Mortimer,2008.0,https://images.gr-assets.com/books/1328167619m...,Imagine you could get into a time machine and ...,"['History', 'Nonfiction', 'Medieval', 'Histori...",224079948,27,3.99,9824,970
3742,"The Everafter War (The Sisters Grimm, #7)","Michael Buckley, Peter Ferguson",2009.0,https://images.gr-assets.com/books/1388278230m...,The Grimm family is caught in the midst of a w...,"['Fantasy', 'Middle Grade', 'Fairy Tales', 'My...",810983559,2,4.32,12493,455
3743,Cinderella Ate My Daughter: Dispatches from th...,Peggy Orenstein,2011.0,https://images.gr-assets.com/books/1279214118m...,The acclaimed author of the groundbreaking bes...,"['Nonfiction', 'Parenting', 'Feminism', 'Psych...",61711527,7,3.65,11279,1988

In [19]:
better_reads_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3744 entries, 0 to 3743
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             3744 non-null   object
 1   author            3744 non-null   object
 2   publishYear       3742 non-null   float64
 3   image             3744 non-null   object
 4   description       3743 non-null   object
 5   genre             3744 non-null   object
 6   ISBN              3627 non-null   object
 7   numberOfEditions  3744 non-null   int64
 8   averageRating     3744 non-null   float64
 9   ratingsCount      3744 non-null   int64
 10  reviewCount       3744 non-null   int64
dtypes: float64(2), int64(3), object(6)
memory usage: 321.9+ KB

In [20]:
# drop rows with NA value
better_reads_df = better_reads_df.dropna()

In [21]:
# drop rows with NA value
better_reads_df

,title,author,publishYear,image,description,genre,ISBN,numberOfEditions,averageRating,ratingsCount,reviewCount
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,2008.0,https://images.gr-assets.com/books/1447303603m...,"Could you survive on your own in the wild, wit...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",439023483,272,4.34,4780653,155254
1,To Kill a Mockingbird,Harper Lee,1960.0,https://images.gr-assets.com/books/1361975680m...,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...",61120081,487,4.25,3198671,72586
2,The Great Gatsby,F. Scott Fitzgerald,1925.0,https://images.gr-assets.com/books/1490528560m...,Alternate Cover Edition ISBN: 0743273567 (ISBN...,"['Classics', 'Fiction', 'School', 'Historical ...",743273567,1356,3.89,2683664,51992
3,The Fault in Our Stars,John Green,2012.0,https://images.gr-assets.com/books/1360206420m...,Despite the tumor-shrinking medical miracle th...,"['Young Adult', 'Romance', 'Fiction', 'Contemp...",525478817,226,4.26,2346404,140739
4,The Hobbit,J.R.R. Tolkien,1937.0,https://images.gr-assets.com/books/1372847500m...,"First published over 50 years ago, J.R.R. Tolk...","['Fantasy', 'Graphic Novels', 'Classics', 'Fic...",618260307,969,4.25,2071616,37653
...,...,...,...,...,...,...,...,...,...,...,...
3739,A Theory of Justice,John Rawls,1971.0,https://s.gr-assets.com/assets/nophoto/book/11...,"Since it appeared in 1971, John Rawls's A Theo...","['Philosophy', 'Politics', 'Nonfiction', 'Law'...",674017722,44,3.91,8472,168
3740,"The Red Knight (The Traitor Son Cycle, #1)",Miles Cameron,2012.0,https://images.gr-assets.com/books/1348037761m...,Twenty eight florins a month is a huge price t...,"['Fantasy', 'Epic Fantasy', 'Fiction', 'High F...",575113294,26,4.12,8556,742
3741,The Time Traveller's Guide to Medieval England...,Ian Mortimer,2008.0,https://images.gr-assets.com/books/1328167619m...,Imagine you could get into a time machine and ...,"['History', 'Nonfiction', 'Medieval', 'Histori...",224079948,27,3.99,9824,970
3742,"The Everafter War (The Sisters Grimm, #7)","Michael Buckley, Peter Ferguson",2009.0,https://images.gr-assets.com/books/1388278230m...,The Grimm family is caught in the midst of a w...,"['Fantasy', 'Middle Grade', 'Fairy Tales', 'My...",810983559,2,4.32,12493,455
3743,Cinderella Ate My Daughter: Dispatches from th...,Peggy Orenstein,2011.0,https://images.gr-assets.com/books/1279214118m...,The acclaimed author of the groundbreaking bes...,"['Nonfiction', 'Parenting', 'Feminism', 'Psych...",61711527,7,3.65,11279,1988

In [22]:
# convert year to int
better_reads_df['publishYear'] = better_reads_df['publishYear'].astype(int)

C:\Users\Helena\AppData\Local\Temp\ipykernel_24940\1019196485.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  better_reads_df['publishYear'] = better_reads_df['publishYear'].astype(int)

In [23]:
better_reads_df

,title,author,publishYear,image,description,genre,ISBN,numberOfEditions,averageRating,ratingsCount,reviewCount
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,2008,https://images.gr-assets.com/books/1447303603m...,"Could you survive on your own in the wild, wit...","['Young Adult', 'Fiction', 'Dystopia', 'Fantas...",439023483,272,4.34,4780653,155254
1,To Kill a Mockingbird,Harper Lee,1960,https://images.gr-assets.com/books/1361975680m...,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...",61120081,487,4.25,3198671,72586
2,The Great Gatsby,F. Scott Fitzgerald,1925,https://images.gr-assets.com/books/1490528560m...,Alternate Cover Edition ISBN: 0743273567 (ISBN...,"['Classics', 'Fiction', 'School', 'Historical ...",743273567,1356,3.89,2683664,51992
3,The Fault in Our Stars,John Green,2012,https://images.gr-assets.com/books/1360206420m...,Despite the tumor-shrinking medical miracle th...,"['Young Adult', 'Romance', 'Fiction', 'Contemp...",525478817,226,4.26,2346404,140739
4,The Hobbit,J.R.R. Tolkien,1937,https://images.gr-assets.com/books/1372847500m...,"First published over 50 years ago, J.R.R. Tolk...","['Fantasy', 'Graphic Novels', 'Classics', 'Fic...",618260307,969,4.25,2071616,37653
...,...,...,...,...,...,...,...,...,...,...,...
3739,A Theory of Justice,John Rawls,1971,https://s.gr-assets.com/assets/nophoto/book/11...,"Since it appeared in 1971, John Rawls's A Theo...","['Philosophy', 'Politics', 'Nonfiction', 'Law'...",674017722,44,3.91,8472,168
3740,"The Red Knight (The Traitor Son Cycle, #1)",Miles Cameron,2012,https://images.gr-assets.com/books/1348037761m...,Twenty eight florins a month is a huge price t...,"['Fantasy', 'Epic Fantasy', 'Fiction', 'High F...",575113294,26,4.12,8556,742
3741,The Time Traveller's Guide to Medieval England...,Ian Mortimer,2008,https://images.gr-assets.com/books/1328167619m...,Imagine you could get into a time machine and ...,"['History', 'Nonfiction', 'Medieval', 'Histori...",224079948,27,3.99,9824,970
3742,"The Everafter War (The Sisters Grimm, #7)","Michael Buckley, Peter Ferguson",2009,https://images.gr-assets.com/books/1388278230m...,The Grimm family is caught in the midst of a w...,"['Fantasy', 'Middle Grade', 'Fairy Tales', 'My...",810983559,2,4.32,12493,455
3743,Cinderella Ate My Daughter: Dispatches from th...,Peggy Orenstein,2011,https://images.gr-assets.com/books/1279214118m...,The acclaimed author of the groundbreaking bes...,"['Nonfiction', 'Parenting', 'Feminism', 'Psych...",61711527,7,3.65,11279,1988

In [24]:
better_reads_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3625 entries, 0 to 3743
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             3625 non-null   object
 1   author            3625 non-null   object
 2   publishYear       3625 non-null   int64
 3   image             3625 non-null   object
 4   description       3625 non-null   object
 5   genre             3625 non-null   object
 6   ISBN              3625 non-null   object
 7   numberOfEditions  3625 non-null   int64
 8   averageRating     3625 non-null   float64
 9   ratingsCount      3625 non-null   int64
 10  reviewCount       3625 non-null   int64
dtypes: float64(1), int64(4), object(6)
memory usage: 339.8+ KB

In [25]:
better_reads_df = better_reads_df.drop_duplicates(subset='ISBN', keep='first')

In [26]:
# change the genre type to list of string
import ast

better_reads_df["genre"] = better_reads_df["genre"].apply(lambda x: ast.literal_eval(x))

In [27]:
better_reads_df

,title,author,publishYear,image,description,genre,ISBN,numberOfEditions,averageRating,ratingsCount,reviewCount
0,"The Hunger Games (The Hunger Games, #1)",Suzanne Collins,2008,https://images.gr-assets.com/books/1447303603m...,"Could you survive on your own in the wild, wit...","[Young Adult, Fiction, Dystopia, Fantasy, Scie...",439023483,272,4.34,4780653,155254
1,To Kill a Mockingbird,Harper Lee,1960,https://images.gr-assets.com/books/1361975680m...,The unforgettable novel of a childhood in a sl...,"[Classics, Fiction, Historical Fiction, School...",61120081,487,4.25,3198671,72586
2,The Great Gatsby,F. Scott Fitzgerald,1925,https://images.gr-assets.com/books/1490528560m...,Alternate Cover Edition ISBN: 0743273567 (ISBN...,"[Classics, Fiction, School, Historical Fiction...",743273567,1356,3.89,2683664,51992
3,The Fault in Our Stars,John Green,2012,https://images.gr-assets.com/books/1360206420m...,Despite the tumor-shrinking medical miracle th...,"[Young Adult, Romance, Fiction, Contemporary, ...",525478817,226,4.26,2346404,140739
4,The Hobbit,J.R.R. Tolkien,1937,https://images.gr-assets.com/books/1372847500m...,"First published over 50 years ago, J.R.R. Tolk...","[Fantasy, Graphic Novels, Classics, Fiction, C...",618260307,969,4.25,2071616,37653
...,...,...,...,...,...,...,...,...,...,...,...
3739,A Theory of Justice,John Rawls,1971,https://s.gr-assets.com/assets/nophoto/book/11...,"Since it appeared in 1971, John Rawls's A Theo...","[Philosophy, Politics, Nonfiction, Law, Classi...",674017722,44,3.91,8472,168
3740,"The Red Knight (The Traitor Son Cycle, #1)",Miles Cameron,2012,https://images.gr-assets.com/books/1348037761m...,Twenty eight florins a month is a huge price t...,"[Fantasy, Epic Fantasy, Fiction, High Fantasy,...",575113294,26,4.12,8556,742
3741,The Time Traveller's Guide to Medieval England...,Ian Mortimer,2008,https://images.gr-assets.com/books/1328167619m...,Imagine you could get into a time machine and ...,"[History, Nonfiction, Medieval, Historical, Br...",224079948,27,3.99,9824,970
3742,"The Everafter War (The Sisters Grimm, #7)","Michael Buckley, Peter Ferguson",2009,https://images.gr-assets.com/books/1388278230m...,The Grimm family is caught in the midst of a w...,"[Fantasy, Middle Grade, Fairy Tales, Mystery, ...",810983559,2,4.32,12493,455
3743,Cinderella Ate My Daughter: Dispatches from th...,Peggy Orenstein,2011,https://images.gr-assets.com/books/1279214118m...,The acclaimed author of the groundbreaking bes...,"[Nonfiction, Parenting, Feminism, Psychology, ...",61711527,7,3.65,11279,1988

In [28]:
# exported to json file
better_reads_df.to_json("better_reads.json", orient="records", indent=4, force_ascii=False)